---
- name: Converge
  hosts: all
  become: yes
  
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      changed_when: false
  
  roles:
    - role: security_baseline
  
  vars:
    security_baseline_backup_configs: false
